- id: demo_post_plus_example
  api:
    base_url: "https://jsonplaceholder.typicode.com/posts/1"
    method: "GET"
    params: {}
    headers: {}
    json_key_map:
      post_id: "id"
      post_title: "title"
      post_body: "body"
      user_id: "userId"
  html:
    url: "https://example.com/"
    selectors:
      site_heading: "h1"
      first_paragraph: "p"
  mapping:
    unified_fields:
      post_id: "api.post_id"
      post_title: "api.post_title"
      post_body: "api.post_body"
      user_id: "api.user_id"
      site_heading: "html.site_heading"
      first_paragraph: "html.first_paragraph"
    field_types:
      post_id: "int"
      user_id: "int"
